# Generated by Django 2.2 on 2020-08-24 12:45

from django.db import migrations, models
import recog.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Handwriting',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to=recog.models.upload)),
                ('text', models.TextField(null=True)),
            ],
        ),
    ]
